name: Scrape LinkedIn Jobs

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm install 
          npm run build
          npm run start:scrapper
          git config user.name scrapper-bot
          git add .
          git commit -m "build: :white_check_mark: updated data"
          git push origin main